[project]
name = "100_community_website"
version = "0.1.0"
description = "Website for Together to 100 Community"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "mypy-extensions>=1.0.0",
    "ruff>=0.11.9",
]
