name: Setup Machine
description: Set up Python and install dependencies

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install uv
        uv venv
        uv pip install .[dev]
