# .github/workflows/cd.yaml
name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  DOCKER_REPO: theitamarshalev/100_community:latest
  CONTAINER_NAME: 100_community
  TARGET_BRANCH: main

jobs:
  build-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
              
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_REPO }} .

      - name: Push Docker image to remote registry
        run: docker push ${{ env.DOCKER_REPO }}

  deploy:
    needs: [build-docker]
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          username: ${{ secrets.USERNAME_SERVER }}
          host: ${{ secrets.HOST_SERVER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop ${{ env.CONTAINER_NAME }} > /dev/null 2>&1 || true
            docker rm -f ${{ env.CONTAINER_NAME }} > /dev/null 2>&1 || true
            docker pull ${{ env.DOCKER_REPO }}
            docker run -d -p 80:80 --name ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_REPO }}
